import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'makagram.settings')
django.setup()

from django.db import connection

def fix_db():
    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS chat_group (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name varchar(100) NOT NULL UNIQUE,
                    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    private boolean NOT NULL DEFAULT false,
                    color varchar(25) NOT NULL DEFAULT 'blue',
                    owner_id integer NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE
                );
                CREATE TABLE IF NOT EXISTS chat_group_members (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    group_id bigint NOT NULL REFERENCES chat_group(id) ON DELETE CASCADE,
                    user_id integer NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
                    CONSTRAINT chat_group_members_uniq UNIQUE (group_id, user_id)
                );
                CREATE TABLE IF NOT EXISTS chat_groupmessage (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    content text NOT NULL,
                    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    author_id integer NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
                    group_id bigint NOT NULL REFERENCES chat_group(id) ON DELETE CASCADE
                );
                CREATE TABLE IF NOT EXISTS chat_groupinvite (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    group_id bigint NOT NULL REFERENCES chat_group(id) ON DELETE CASCADE,
                    invited_by_id integer NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
                    invitee_id integer NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
                    CONSTRAINT chat_groupinvite_uniq UNIQUE (group_id, invitee_id)
                );
                ALTER TABLE chat_group ADD COLUMN IF NOT EXISTS color varchar(25) NOT NULL DEFAULT 'blue';
                ALTER TABLE chat_group ADD COLUMN IF NOT EXISTS private boolean NOT NULL DEFAULT false;
            """)
        else:
            statements = [
                """CREATE TABLE IF NOT EXISTS chat_group (
                    id integer PRIMARY KEY AUTOINCREMENT,
                    name varchar(100) NOT NULL UNIQUE,
                    created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    private boolean NOT NULL DEFAULT 0,
                    color varchar(25) NOT NULL DEFAULT 'blue',
                    owner_id integer NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE
                );""",
                """CREATE TABLE IF NOT EXISTS chat_group_members (
                    id integer PRIMARY KEY AUTOINCREMENT,
                    group_id integer NOT NULL REFERENCES chat_group(id) ON DELETE CASCADE,
                    user_id integer NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
                    UNIQUE (group_id, user_id)
                );""",
                """CREATE TABLE IF NOT EXISTS chat_groupmessage (
                    id integer PRIMARY KEY AUTOINCREMENT,
                    content text NOT NULL,
                    created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    author_id integer NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
                    group_id integer NOT NULL REFERENCES chat_group(id) ON DELETE CASCADE
                );""",
                """CREATE TABLE IF NOT EXISTS chat_groupinvite (
                    id integer PRIMARY KEY AUTOINCREMENT,
                    created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    group_id integer NOT NULL REFERENCES chat_group(id) ON DELETE CASCADE,
                    invited_by_id integer NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
                    invitee_id integer NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
                    UNIQUE (group_id, invitee_id)
                );"""
            ]
            for stmt in statements:
                cursor.execute(stmt)

if __name__ == '__main__':
    fix_db()
