# Generated by Django 6.0.5 on 2026-09-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='is_super',
            field=models.BooleanField(default=False),
        ),
    ]
