# Generated by Django 6.0.5 on 2026-09-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_achievement_is_super'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='is_super',
        ),
        migrations.AddField(
            model_name='achievement',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievement',
            name='type',
            field=models.CharField(default='common', max_length=10),
        ),
    ]
