# Generated by Django 6.0.5 on 2026-08-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_groupinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='color',
            field=models.CharField(default='blue', max_length=25),
        ),
        migrations.AlterField(
            model_name='group',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
