# Generated by Django 6.0.5 on 2026-08-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_create_missing_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members_can_invite',
            field=models.BooleanField(default=False),
        ),
    ]
