# Generated by Django 6.0.5 on 2026-08-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_notification_notificationmute'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationmute',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='notificationmute',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotificationMute',
        ),
    ]
