# Generated by Django 6.0.5 on 2026-09-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='file',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_data',
            field=models.BinaryField(null=True),
        ),
    ]
