# Generated by Django 6.0.5 on 2026-08-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
