# Generated by Django 6.0.5 on 2026-09-12 16:59

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='mfa_secret',
            field=models.CharField(db_index=True, default=pyotp.random_base32, max_length=32),
        ),
    ]
