# Generated by Django 6.0.5 on 2026-08-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color',
            field=models.CharField(default='blue', max_length=25),
        ),
    ]
