# Generated by Django 6.0.5 on 2026-09-17 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('makagram', '0002_profile_mfa_enabled_profile_mfa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='equipped_achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_profiles', to='achievements.achievement'),
        ),
    ]
