# Generated by Django 6.0.5 on 2026-08-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makagram', '0002_profile_avatar_name_profile_avatar_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
