# Generated by Django 6.0.5 on 2026-08-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makagram', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
