# Generated by Django 6.0.5 on 2026-08-27 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelpostlike',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channelpostlike',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='channelpostlike',
            unique_together={('post', 'creator')},
        ),
    ]
